version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:latest

orbs:
  aws-cli: circleci/aws-cli@5.2.0
  sam: circleci/aws-sam-serverless@6.1.0
  python: circleci/python@3.0.0


jobs:
  build-layer:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: mkdir -p infra/src/layer/python/lib/python3.12/site-packages 
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: infra/src/requirements.txt
          args: '-t infra/src/layer/python/lib/python3.12/site-packages'
      - persist_to_workspace:
          root: infra/src/
          paths: 
            - layer

  deploy-serverless:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - attach_workspace:
          at: infra/src/
      - run: ls -la infra/src/layer # Debugging: Ensure layer exists
      - aws-cli/setup:
          aws_access_key_id: ${AWS_ACCESS_KEY}
          aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          region: ${AWS_REGION}
      - sam/install
      - sam/deploy:
          capabilities: CAPABILITY_IAM
          region: ${AWS_REGION}
          resolve_s3: true
          stack_name: infra
          template: infra/template.yaml
          no_fail_on_empty_changeset: true
          arguments: "--no-confirm-changeset"
   
  deploy-cluster:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Detect Changed Cluster and Deploy
          command: |
            git fetch origin $CIRCLE_BRANCH --depth=1 --quiet
            CHANGED_FILE=$(git diff --name-only origin/$CIRCLE_BRANCH HEAD | grep -E '^clusters/.+\.tfvars$' | head -n 1)

            if [[ -z "$CHANGED_FILE" ]]; then
              echo "No cluster changes detected. Exiting."
              exit 0
            fi

            CLUSTER_NAME=$(echo "$CHANGED_FILE" | sed -E 's|clusters/(.+)\.tfvars|\1|')

            echo "Deploying cluster: $CLUSTER_NAME"

            terraform init
            terraform apply -var-file=clusters/$CLUSTER_NAME.tfvars -auto-approve

workflows:
  # build_and_deploy_sam:
  #   jobs:
  #     - build-layer
  #     - deploy-serverless:
  #         requires:
  #           - build-layer
  deploy_tf_rds_cluster:
    jobs:
      - deploy-cluster:
          filters:
            branches:
              only: test
              
