version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@6.1.0
  aws-cli: circleci/aws-cli@5.2.0
  terraform: circleci/terraform@3.6.0
  python: circleci/python@3.0.0

jobs:
  build-layer:
    executor: python/3.12
    steps:
      - checkout
      - run: mkdir -p infra/src/layer/python/lib/python3.12/site-packages 
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: infra/src/requirements.txt
          args: '-t infra/src/layer/python/lib/python3.12/site-packages'
      - persist_to_workspace:
          root: infra/src/
          paths: 
            - layer
  deploy-wrapper:
    docker:
      - image: cimg/python3.12
    steps:
      - attach_workspace:
          at: infra/src/
      - run: ls -la infra/src/layer
      - sam/deploy:
          requires:
            - build-layer
          auth:
            - aws-cli/setup:
                aws_access_key_id: ${AWS_ACCESS_KEY}
                aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
                region: eu-west-${AWS_REGION}
          base_dir: infra/
          template: infra/template.yaml
          stack_name: infra
          region: eu-west-1
          validate: false
          resolve_s3: true


workflows:
  build-and-deploy-sam:
    jobs:
      - build-layer
      - deploy-wrapper
          