version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@6.1.0
  aws-cli: circleci/aws-cli@5.2.0
  terraform: circleci/terraform@3.6.0
  python: circleci/python@3.0.0

workflows:
  build_and_deploy_sam:
    jobs:
      - sam/deploy:
          auth:
            - aws-cli/setup:
              access_key_id: AKIATX3PH5WFKTZTMBE4
              aws_secret_access_key: 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
              region: eu-west-1
          base_dir: infra/
          template: infra/template.yaml
          stack_name: infra
          region: eu-west-1
          validate: false
          