version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@6.1.0
  aws-cli: circleci/aws-cli@5.2.0
  terraform: circleci/terraform@3.6.0
  python: circleci/python@3.0.0

workflows:
  build_and_deploy_sam:
    jobs:
      - sam/deploy:
          auth:
            - aws-cli/setup:
              access_key_id: AKIATX3PH5WFL5UEAENZ
              aws_secret_access_key: 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
              region: eu-west-1
          base_dir: infra/
          template: infra/template.yaml
          stack_name: infra
          region: eu-west-1
          validate: false
          resolve_s3: true
          